local importedInSession = false

local function isAccountItem(name)
    return QBX.Shared.AccountItems[name] == true
end

local function sortedStringKeys(values)
    local keys = {}
    for key in pairs(values) do keys[#keys + 1] = key end
    table.sort(keys)
    return keys
end

local function serializeLuaTable(value, indent)
    indent = indent or 0
    local pad = string.rep(' ', indent)
    local childPad = string.rep(' ', indent + 4)
    local lines = { '{' }

    for _, key in ipairs(sortedStringKeys(value)) do
        local child = value[key]
        local serialized
        if type(child) == 'string' then
            serialized = string.format('%q', child)
        elseif type(child) == 'number' or type(child) == 'boolean' then
            serialized = tostring(child)
        elseif type(child) == 'table' then
            serialized = serializeLuaTable(child, indent + 4)
        else
            error(('cannot serialize item field %s (%s)'):format(key, type(child)))
        end
        lines[#lines + 1] = ('%s[%q] = %s,'):format(childPad, key, serialized)
    end

    lines[#lines + 1] = pad .. '}'
    return table.concat(lines, '\n')
end

local function itemDefinition(name, data, itemType)
    name = tostring(data.name or name):lower()
    return {
        name = name,
        label = tostring(data.label or name),
        weight = tonumber(data.weight) or 0,
        type = itemType or 'item',
        ammotype = data.ammoname or data.ammotype,
        image = data.client and data.client.image or (name .. '.png'),
        unique = itemType ~= 'item' or data.stack == false,
        useable = itemType == 'item' and data.useable ~= false,
        shouldClose = data.close ~= false,
        description = tostring(data.description or ''),
    }
end

local function importOxItems()
    if GetResourceState('ox_inventory') ~= 'started' then
        error('start ox_inventory before running qbx_importOxItems')
    end
    if importedInSession or next(require 'shared.items_imported') then
        error('shared/items_imported.lua already contains imported items; review it or restore the file before importing again')
    end

    local oxItems = exports.ox_inventory:Items()
    if type(oxItems) ~= 'table' then error('ox_inventory:Items() did not return an item table') end

    local imported = {}
    for name, data in pairs(oxItems) do
        if type(name) == 'string' and type(data) == 'table' then
            local item = itemDefinition(name, data)
            if not isAccountItem(item.name) and QBX.Shared.Items[item.name] == nil then imported[item.name] = item end
        end
    end

    local ok, oxWeapons = pcall(require, '@ox_inventory.data.weapons')
    if ok and type(oxWeapons) == 'table' then
        for name, data in pairs(oxWeapons.Weapons or {}) do
            if type(name) == 'string' and type(data) == 'table' then
                local item = itemDefinition(name, data, 'weapon')
                if not isAccountItem(item.name) and QBX.Shared.Items[item.name] == nil then imported[item.name] = item end
            end
        end
        for name, data in pairs(oxWeapons.Components or {}) do
            if type(name) == 'string' and type(data) == 'table' then
                local item = itemDefinition(name, data, 'component')
                if not isAccountItem(item.name) and QBX.Shared.Items[item.name] == nil then imported[item.name] = item end
            end
        end
        for name, data in pairs(oxWeapons.Ammo or {}) do
            if type(name) == 'string' and type(data) == 'table' then
                local item = itemDefinition(name, data, 'ammo')
                if not isAccountItem(item.name) and QBX.Shared.Items[item.name] == nil then imported[item.name] = item end
            end
        end
    else
        lib.print.warn('Could not read ox_inventory/data/weapons.lua; weapon items from qbx_core/shared/weapons.lua will be added with default weight and images')
    end

    for _, weapon in pairs(QBX.Shared.Weapons) do
        local name = type(weapon.name) == 'string' and weapon.name:lower()
        if name and QBX.Shared.Items[name] == nil and imported[name] == nil then
            imported[name] = {
                name = name,
                label = weapon.label,
                weight = 0,
                type = 'weapon',
                ammotype = weapon.ammotype,
                image = name .. '.png',
                unique = true,
                useable = false,
                shouldClose = true,
                description = '',
            }
        end
    end

    local source = '-- Generated by qbx_importOxItems. Review callback behavior and keep local changes in shared/items.lua.\nreturn ' .. serializeLuaTable(imported, 0) .. '\n'
    if not SaveResourceFile(GetCurrentResourceName(), 'shared/items_imported.lua', source, -1) then
        error('failed to write shared/items_imported.lua')
    end

    for name, data in pairs(imported) do QBX.Shared.Items[name] = data end
    importedInSession = true
    TriggerClientEvent('QBCore:Client:OnSharedUpdateMultiple', -1, 'Items', imported)
    TriggerEvent('QBCore:Server:UpdateObject')
    local importedCount = 0
    for _ in pairs(imported) do importedCount = importedCount + 1 end
    lib.print.info(('Imported %d item definitions from ox_inventory into shared/items_imported.lua. Review callbacks and restart qbx_core plus peak-qb-inventory before removing ox_inventory.'):format(importedCount))
end

RegisterCommand('qbx_importOxItems', function(source)
    if source ~= 0 then return lib.print.warn('qbx_importOxItems can only be run from the server console') end
    local ok, err = pcall(importOxItems)
    if not ok then lib.print.error(('Item import stopped: %s'):format(err)) end
end, true)

local function tableExists(tableName)
    return (tonumber(MySQL.scalar.await('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?', { tableName })) or 0) > 0
end

local function columnExists(tableName, columnName)
    return (tonumber(MySQL.scalar.await([[SELECT COUNT(*) FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?]], { tableName, columnName })) or 0) > 0
end

local function backupTable(sourceTable, runId, backupNames)
    if not tableExists(sourceTable) then error(('source table %s was not found'):format(sourceTable)) end
    local backupTableName = ('qbxpk_mig_%s_%s'):format(runId, sourceTable == 'player_vehicles' and 'vehicles' or sourceTable)
    if tableExists(backupTableName) then
        error(('backup table %s already exists; refusing to reuse it'):format(backupTableName))
    end
    MySQL.query.await(('CREATE TABLE `%s` LIKE `%s`'):format(backupTableName, sourceTable))
    MySQL.query.await(('INSERT INTO `%s` SELECT * FROM `%s`'):format(backupTableName, sourceTable))
    backupNames[sourceTable] = backupTableName
    return backupTableName
end

local function decodeCollection(raw, context)
    if raw == nil or raw == '' or raw == 'null' then return {} end
    local ok, decoded = pcall(json.decode, raw)
    if not ok or type(decoded) ~= 'table' then
        return nil, ('%s contains invalid JSON inventory data'):format(context)
    end
    return decoded
end

local function convertItems(rawItems, context, accountItems, maxSlots)
    if type(rawItems) ~= 'table' then return nil, ('%s is not an item list'):format(context) end
    local converted, slots, accountTotals, totalWeight = {}, {}, {}, 0

    for key, record in pairs(rawItems) do
        if type(record) ~= 'table' then return nil, ('%s contains a non-item record'):format(context) end
        local name = type(record.name) == 'string' and record.name:lower()
        if not name then return nil, ('%s contains an item with an invalid name'):format(context) end

        local slot = tonumber(record.slot or key)
        if not slot or slot < 1 or slot % 1 ~= 0 then return nil, ('%s contains an invalid slot for %s'):format(context, name) end
        if slots[slot] then return nil, ('%s contains duplicate slot %s'):format(context, slot) end
        slots[slot] = true

        local amount = tonumber(record.count or record.amount)
        if not amount or amount < 1 or amount % 1 ~= 0 then return nil, ('%s contains invalid amount for %s in slot %s'):format(context, name, slot) end
        local metadata = record.metadata
        if metadata == nil then metadata = record.info end
        if metadata == nil then metadata = {} end
        if type(metadata) ~= 'table' then return nil, ('%s contains invalid metadata for %s in slot %s'):format(context, name, slot) end

        if maxSlots and slot > maxSlots then
            return nil, ('%s uses slot %s, above the configured Peak capacity of %s slots'):format(context, slot, maxSlots)
        end

        local moneyType = accountItems and accountItems[name]
        if moneyType then
            accountTotals[moneyType] = (accountTotals[moneyType] or 0) + amount
        else
            local definition = QBX.Shared.Items[name]
            if not definition then return nil, ('%s contains unknown item %s'):format(context, tostring(record.name)) end
            if definition.unique == true and amount ~= 1 then
                return nil, ('%s contains %s units of unique item %s in slot %s'):format(context, amount, name, slot)
            end
            local weight = tonumber(definition.weight) or 0
            if weight < 0 then return nil, ('%s has an invalid negative weight for %s'):format(context, name) end
            totalWeight = totalWeight + weight * amount

            converted[#converted + 1] = {
                name = name,
                amount = amount,
                info = metadata,
                label = definition.label,
                description = definition.description or '',
                weight = weight,
                type = definition.type or 'item',
                unique = definition.unique == true,
                useable = definition.useable ~= false,
                image = definition.image or (name .. '.png'),
                shouldClose = definition.shouldClose ~= false,
                slot = slot,
                combinable = definition.combinable,
            }
        end
    end

    table.sort(converted, function(left, right) return left.slot < right.slot end)
    return converted, nil, accountTotals, totalWeight
end

local function stashIdentifier(owner, name)
    if owner ~= nil and type(owner) ~= 'string' then error('stash owner must be a string or nil') end
    if type(name) ~= 'string' or name == '' then error('stash name must be a non-empty string') end
    owner = owner or ''
    return ('oxstash:%d:%s:%d:%s'):format(#owner, owner, #name, name)
end

exports('GetMigratedStashId', function(owner, name)
    return stashIdentifier(owner, name)
end)

local function hasItems(raw, context)
    local items, err = decodeCollection(raw, context)
    if not items then return nil, err end
    return next(items) ~= nil, items
end

local function migrateOxInventories()
    if GetResourceState('ox_inventory') ~= 'started' then
        error('start ox_inventory before running qbx_migrateOxInventory')
    end
    if next(require 'shared.items_imported') == nil and next(QBX.Shared.Items) == nil then
        error('import and review item definitions before migrating inventories')
    end
    if #GetPlayers() > 0 then error('stop or disconnect all player sessions before migrating player inventories') end

    if not tableExists('players') then error('players table was not found') end

    local hasVehicles = tableExists('player_vehicles')
    if hasVehicles then
        for _, column in ipairs({ 'id', 'plate', 'glovebox', 'trunk' }) do
            if not columnExists('player_vehicles', column) then
                error(('player_vehicles.%s is missing; start ox_inventory so it can prepare the Qbox vehicle columns before migration'):format(column))
            end
        end
    end

    local runId = os.date('!%y%m%d%H%M%S') .. ('%05d'):format(GetGameTimer() % 100000)
    local backupNames = {}
    backupTable('players', runId, backupNames)

    local hasOxStashes = tableExists('ox_inventory')
    if hasOxStashes then backupTable('ox_inventory', runId, backupNames) end

    if hasVehicles then backupTable('player_vehicles', runId, backupNames) end

    local hasInventories = tableExists('inventories')
    if hasInventories then
        backupTable('inventories', runId, backupNames)
    else
        MySQL.query.await([[CREATE TABLE `inventories` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `identifier` varchar(255) NOT NULL,
            `items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
            PRIMARY KEY (`identifier`),
            KEY `id` (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci]])
    end

    local maxStashSlots = GetConvarInt('qbx:peakStashMaxSlots', 100)
    if maxStashSlots < 1 then error('qbx:peakStashMaxSlots must be a positive integer') end
    local maxPlayerSlots = GetConvarInt('qbx:peakMaxSlots', 111)
    if maxPlayerSlots < 1 then error('qbx:peakMaxSlots must be a positive integer') end
    local maxPlayerWeight = GetConvarInt('qbx:peakMaxWeight', 120000)
    if maxPlayerWeight < 1 then error('qbx:peakMaxWeight must be a positive integer') end

    local targets, playerUpdates, validationErrors, playerCount = {}, {}, {}, 0
    local accountItems = QBX.Shared.AccountItemAccounts
    local playerRows = MySQL.query.await('SELECT citizenid, money, inventory FROM players WHERE inventory IS NOT NULL AND inventory <> ""')
    for i = 1, #playerRows do
        local row = playerRows[i]
        local raw, err = decodeCollection(row.inventory, ('player %s'):format(row.citizenid))
        if not raw then
            validationErrors[#validationErrors + 1] = err
        else
            local context = ('player %s'):format(row.citizenid)
            local converted, convertErr, accountTotals, totalWeight = convertItems(raw, context, accountItems, maxPlayerSlots)
            if convertErr then
                validationErrors[#validationErrors + 1] = convertErr
            elseif totalWeight > maxPlayerWeight then
                validationErrors[#validationErrors + 1] = ('%s has weight %s, above the configured Peak capacity of %s'):format(context, totalWeight, maxPlayerWeight)
            else
                local hasAccountItems = next(accountTotals) ~= nil
                local balances, accountDataValid = nil, true
                if hasAccountItems then
                    balances, err = decodeCollection(row.money, ('player %s money accounts'):format(row.citizenid))
                    if not balances then
                        validationErrors[#validationErrors + 1] = err
                        accountDataValid = false
                    else
                        for moneyType, amount in pairs(accountTotals) do
                            local balance = tonumber(balances[moneyType]) or 0
                            if balance ~= balance or balance ~= amount then
                                validationErrors[#validationErrors + 1] = ('%s has %s account items (%s) but players.money.%s is %s; reconcile manually before migration'):format(context, moneyType, amount, moneyType, tostring(balances[moneyType]))
                                accountDataValid = false
                            end
                        end
                    end
                end

                if accountDataValid then
                    playerUpdates[#playerUpdates + 1] = {
                        query = 'UPDATE players SET inventory = ? WHERE citizenid = ?',
                        values = { json.encode(converted), row.citizenid },
                    }
                    playerCount = playerCount + 1
                end
            end
        end
    end

    if hasOxStashes then
        local stashRows = MySQL.query.await('SELECT owner, name, data FROM ox_inventory')
        for i = 1, #stashRows do
            local row = stashRows[i]
            local context = ('ox stash %s (owner %s)'):format(row.name, row.owner or '')
            local nonempty, rawOrError = hasItems(row.data, context)
            if nonempty == nil then
                validationErrors[#validationErrors + 1] = rawOrError
            elseif nonempty then
                local converted, err = convertItems(rawOrError, context, nil, maxStashSlots)
                if err then
                    validationErrors[#validationErrors + 1] = err
                else
                    targets[#targets + 1] = { identifier = stashIdentifier(row.owner, row.name), items = converted, context = context }
                end
            end
        end
    end

    if hasVehicles then
        local vehicleRows = MySQL.query.await('SELECT id, plate, glovebox, trunk FROM player_vehicles')
        local plateCounts, normalizedPlates = {}, {}
        for i = 1, #vehicleRows do
            local plate = tostring(vehicleRows[i].plate or ''):gsub('^%s+', ''):gsub('%s+$', ''):upper()
            normalizedPlates[i] = plate
            if plate ~= '' then plateCounts[plate] = (plateCounts[plate] or 0) + 1 end
        end

        for i = 1, #vehicleRows do
            local row = vehicleRows[i]
            for _, field in ipairs({ 'glovebox', 'trunk' }) do
                local context = ('vehicle %s %s'):format(row.id, field)
                local nonempty, rawOrError = hasItems(row[field], context)
                if nonempty == nil then
                    validationErrors[#validationErrors + 1] = rawOrError
                elseif nonempty then
                    local plate = normalizedPlates[i]
                    if plate == '' then
                        validationErrors[#validationErrors + 1] = ('%s has items but its plate is blank'):format(context)
                    elseif plateCounts[plate] > 1 then
                        validationErrors[#validationErrors + 1] = ('%s has items but plate %s is duplicated'):format(context, plate)
                    else
                        local converted, err = convertItems(rawOrError, context, nil, maxStashSlots)
                        if err then
                            validationErrors[#validationErrors + 1] = err
                        else
                            local prefix = field == 'trunk' and 'trunk-' or 'glovebox-'
                            targets[#targets + 1] = { identifier = prefix .. plate, items = converted, context = context }
                        end
                    end
                end
            end
        end
    end

    if #validationErrors > 0 then
        error(('validation stopped migration (%d issue(s)); source data is unchanged and backups were created:\n- %s'):format(#validationErrors, table.concat(validationErrors, '\n- ')))
    end

    local targetByIdentifier = {}
    for i = 1, #targets do
        local target = targets[i]
        if #target.identifier > 255 then error(('target key is too long for %s'):format(target.context)) end
        if targetByIdentifier[target.identifier] then error(('multiple source inventories map to %s'):format(target.identifier)) end
        targetByIdentifier[target.identifier] = target
    end

    local existingTargets = MySQL.query.await([[SELECT identifier, items FROM inventories
        WHERE identifier LIKE 'oxstash:%' OR identifier LIKE 'trunk-%' OR identifier LIKE 'glovebox-%']])
    for i = 1, #existingTargets do
        local row = existingTargets[i]
        local target = targetByIdentifier[row.identifier]
        if target then
            local existingItems, err = decodeCollection(row.items, ('existing inventory %s'):format(row.identifier))
            if not existingItems then error(err) end
            local normalized, convertErr = convertItems(existingItems, ('existing inventory %s'):format(row.identifier))
            if convertErr then error(convertErr) end
            if json.encode(normalized) ~= json.encode(target.items) then
                error(('target inventory %s already exists with different contents; no rows were changed'):format(row.identifier))
            end
            target.alreadyPresent = true
        end
    end

    local identifierLength = tonumber(MySQL.scalar.await([[SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'inventories' AND COLUMN_NAME = 'identifier']])) or 0
    for identifier in pairs(targetByIdentifier) do
        if #identifier > identifierLength then
            error(('inventories.identifier allows %s characters but migration needs %s; widen the column and rerun'):format(identifierLength, #identifier))
        end
    end

    local queries, migratedCount, skippedCount = {}, 0, 0
    for i = 1, #playerUpdates do queries[#queries + 1] = playerUpdates[i] end
    for i = 1, #targets do
        local target = targets[i]
        if target.alreadyPresent then
            skippedCount = skippedCount + 1
        else
            queries[#queries + 1] = {
                query = 'INSERT INTO inventories (identifier, items) VALUES (?, ?)',
                values = { target.identifier, json.encode(target.items) },
            }
            migratedCount = migratedCount + 1
        end
    end

    if #GetPlayers() > 0 then error('a player session appeared during migration validation; no inventory rows were changed') end

    if #queries > 0 and not MySQL.transaction.await(queries) then
        error('database transaction failed; all source changes were rolled back and backups remain available')
    end

    local backupSummary = {}
    for sourceTable, backupName in pairs(backupNames) do
        backupSummary[#backupSummary + 1] = ('%s -> %s'):format(sourceTable, backupName)
    end
    table.sort(backupSummary)
    lib.print.info(('Migration normalized %d player inventories, copied %d stash/vehicle inventories (%d already matched). Backups: %s'):format(playerCount, migratedCount, skippedCount, table.concat(backupSummary, ', ')))
    lib.print.info(('Player inventories were converted to QB records; account items matching players.money were removed after exact balance checks. Stash slots were validated against %d; player slots and weight against %d and %d. Restart peak-qb-inventory to load migrated stash and vehicle rows.'):format(maxStashSlots, maxPlayerSlots, maxPlayerWeight))
end

RegisterCommand('qbx_migrateOxInventory', function(source)
    if source ~= 0 then return lib.print.warn('qbx_migrateOxInventory can only be run from the server console') end
    if QBX.InventoryMigrationInProgress then return lib.print.warn('An inventory migration is already in progress') end
    if #GetPlayers() > 0 then return lib.print.error('Stop or disconnect all player sessions before migrating player inventories') end
    QBX.InventoryMigrationInProgress = true
    local ok, err = pcall(migrateOxInventories)
    QBX.InventoryMigrationInProgress = false
    if not ok then lib.print.error(('Inventory migration stopped safely: %s'):format(err)) end
end, true)
